<div class="container">
    <div class="span12">
        <div class="col-lg-9 col-md-8 col-sm-10 col-xs-12 financiamento-box">


            <h2>Financiamento</h2>
            <h3>Escolha abaixo o banco de sua preferência e simule um financiamento.</h3>

            <ul class="financiamento">
                <li>
                    <a href="http://www.shopcredit.com.br/shopcredit/index_ib.asp?diret=PessoaFisica&amp;abrepag=credimobhomepf.asp"><img src="res/imgs/simular_bradesco.png" height="100" width="160"></a>
                </li>
                <li>
                    <a href="https://ww3.itau.com.br/imobline/pre/simuladores_new/index.aspx?IDENT_bkl=pre&amp;IMOB_tipobkl="><img src="res/imgs/simular_itau.png" height="100" width="160"></a>
                </li>
                <li>
                    <a href="http://www8.caixa.gov.br/siopiinternet/simulaOperacaoInternet.do?method=inicializarCasoUso"><img src="res/imgs/simular_caixa.png" height="100" width="160"></a>
                </li>
                <li>
                    <a href="http://www.bb.com.br/portalbb/page65,116,2171,1,1,1,1.bb?codigoNoticia=6124&amp;codigoMenu=184&amp;codigoRet=4921&amp;bread=1_1"><img src="res/imgs/simular_bb.png" height="100" width="160"></a>
                </li>
                <li>
                    <a href="http://www.bancoreal.com.br/index_internas.htm?sUrl=http://www.bancoreal.com.br/pessoas/credito_imobiliario/tpl_cred_imob_simuladores.shtm"><img src="res/imgs/simular_real.png" height="100" width="160"></a>
                </li>
                <li>
                    <a href="http://www.santander.com.br/portal/gsb/script/templates/GCMRequest.do?page=2671&amp;entryID=3458"><img src="res/imgs/simular_santander.png" height="100" width="160"></a>
                </li>
                <li>
                    <a href="https://wwws3.hsbc.com.br/HPB-CHM-SIMULADOR/servlets/HPBCreditoImobiliarioServlet"><img src="res/imgs/simular_hsbc.png" height="100" width="160"></a>
                </li>
                <li>
                    <a href="http://www.banrisul.com.br/brz/link/brzw01hw.asp?css=bob&amp;secao_id=1083"><img src="res/imgs/simular_banrisul.png" height="100" width="160"></a>
                </li>

            </ul>

        </div>
    </div>
</div>