<footer class="footer-site">
    <div class="footer-fone">
        <div class="container">
            <h6>
                <img src="<?php echo $this->serverUrl() . BASEDIR ?>/res/imgs/telefone-branco.png" alt="Telefone"/>
                LIGUE AGORA <strong>51 3661 1040</strong>
            </h6>
        </div>
    </div>
    <div class="footer-content">
        <div class="container">
            <div class="logo-footer">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR ?>/res/imgs/logo.png" alt="Esselence"/></a>
            </div>
            <div class="address-footer">
                <address>
                    Rua Fernando Amaral, 1038 - Sala 01 - Tramandaí - RS<br/>
                    Telefone: 51 3661 1040
                </address>
                <a href="mailto:vendas@esselence.com.br">vendas@esselence.com.br</a>
            </div>
            <div class="facebook-plugin">
                <span class="icon-facebook"></span>
                <div class="fb-page" data-href="https://www.facebook.com/www.esselence.com.br?fref=ts" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="false" data-show-posts="false"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/www.esselence.com.br?fref=ts"><a href="https://www.facebook.com/www.esselence.com.br?fref=ts">Esselence Consultoria Imobiliária</a></blockquote></div></div>
            </div>
        </div>
    </div>
</footer>