<header class="header-site">
    <div id="menutop" class="nav-bar">
        <div class="container">
            <button type="button" class="open-menu"><i class="icon-menu"></i></button>
            <div class="logo">
                <a href="<?php echo $this->serverUrl().BASEDIR?>/"><img src="<?php echo $this->serverUrl() . BASEDIR ?>/res/imgs/logo3.png" style="max-height: 150px" alt="Esselence"/></a>
            </div>
            <div id="menu" class="menu" >
                <nav class="nav-main">
                    <ul>
                        <li><a href="<?php echo $this->serverUrl().BASEDIR?>/imoveis/listagem?tipo=Empreendimento">Lançamentos</a></li>
                        <li><a href="<?php echo $this->serverUrl().BASEDIR?>/imoveis/listagem?status=Venda">Imóveis à venda</a></li>
                        <li><a href="<?php echo $this->serverUrl().BASEDIR?>/fale-conosco">Fale conosco</a></li>
                    </ul>
                </nav>
                <div class="nav-secondary">
                    <div>
                        <a href="<?php echo $this->serverUrl().BASEDIR?>/quem-somos">Quem somos</a>
                    </div>
                    <div>
                        <a href="<?php echo $this->serverUrl().BASEDIR?>/fale-conosco">Anuncie seu imóvel</a>
                    </div>
                    <div>
                        <a href="<?php echo $this->serverUrl().BASEDIR?>/financiamento">Financiamento</a>
                    </div>
                </div>
            </div>
            <div class="fone-header" >
                <a href="tel:51 3661 1040"><img src="<?php echo $this->serverUrl() . BASEDIR ?>/res/imgs/telefone.png" alt="Telefone"/></a>
                <img src="<?php echo $this->serverUrl() . BASEDIR ?>/res/imgs/telefone.png" alt="Telefone"/>
                <span class="fone-text">
                    Ligue agora
                    <strong>51 3661 1040</strong>
                </span>
            </div>
        </div>
    </div>
</header>
