<header class="header-site">
    <div class="nav-bar">
        <div class="container">
            <button type="button" class="open-menu"><i class="icon-menu"></i></button>
            <div class="logo">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR ?>/res/imgs/logo.png" alt="Esselence"/></a>
            </div>
            <div class="menu">
                <nav class="nav-main">
                    <ul>
                        <li><a href="#">Lançamentos</a></li>
                        <li><a href="#">Imóveis à venda</a></li>
                        <li><a href="#">Fale conosco</a></li>
                    </ul>
                </nav>
                <div class="nav-secondary">
                    <div>
                        <a href="#">Quem somos</a>
                    </div>
                    <div>
                        <a href="#">Anuncie seu imóvel</a>
                    </div>
                    <div>
                        <a href="#">Financiamento</a>
                    </div>
                </div>
            </div>
            <div class="fone-header">
                <a href="tel:51 3661 1040"><img src="<?php echo $this->serverUrl() . BASEDIR ?>/res/imgs/telefone.png" alt="Telefone"/></a>
                <img src="<?php echo $this->serverUrl() . BASEDIR ?>/res/imgs/telefone.png" alt="Telefone"/>
                <span class="fone-text">
                    Ligue agora
                    <strong>51 3661 1040</strong>
                </span>
            </div>
        </div>
    </div>
</header>
