<!DOCTYPE html>
<html>
<head lang="pt-BR">
    <title>Esselence Imóveis | Tramandaí, RS</title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Esselence Imóveis em Tramandaí - RS, Imóveis em Tramandaí, Imóveis no litoral Norte do RS, Venda de imóveis, Apartamentos, Casas, Terrenos, Lançamentos">
    <meta name="revisit-after" content="1" />
    <meta name="language" content="pt-br" />

    <link rel="shortcut icon" href="favicon.ico">

    <link rel="stylesheet" href="<?php echo $this->serverUrl() . BASEDIR ?>/res/css/style.css"/>
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700' rel='stylesheet' type='text/css'>
    <?php echo $this->headLink()?>

    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript" src="<?php echo $this->serverUrl() . BASEDIR ?>/res/js/gmaps.js"></script>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.4&appId=712673535512368";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
</head>
<body>

<!-- HEADER -->
<?php echo $this->render('header.phtml'); ?>
<!-- HEADER -->

<section class="body-site">
    <?php echo $this->layout()->content;?>
</section>

<!-- FOOTER -->
<?php echo $this->render('footer.phtml'); ?>
<!-- /FOOTER -->

</body>
<script src="<?php echo $this->serverUrl() . BASEDIR ;?>/res/js/main.min.js"></script>
<?php echo $this->headScript()?>

<!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
    window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
        d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
        _.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
        $.src="//v2.zopim.com/?3DI8nSKrI1XWuYIohXQOruptdMtFZc5I";z.t=+new Date;$.
            type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
</script>
<!--End of Zopim Live Chat Script-->

</html>