<?php
    $params = Zend_Controller_Front::getInstance()->getRequest()->getParams();
    $dorms  = isset($params['dormitorios']) ? explode(',', $params['dormitorios']) : array();
?>
<div class="pesquisa-container col-lg-3 col-md-4 col-sm-12">
    <div class="<?php echo !empty($this->innerDivClass) ? $this->innerDivClass : 'pesquisa-home'?>">
        <div class="formulario">
            <form action="<?php echo $this->serverUrl().BASEDIR?>/imoveis/listagem">
                <h2>Encontre seu imóvel</h2>
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-12">
                        <div class="form-group">
                            <label for="tipo">Tipos</label>
                            <div class="custom-select">
                                <select class="form-control" name="tipo" id="tipo">
                                    <option value="">Selecione</option>
                                    <?php foreach ($this->listas['Categoria'] as $categoria) : ?>
                                        <option value="<?= $categoria ?>"<?php if(array_key_exists('tipo', $params) && $params['tipo'] == $categoria):?> selected<?php endif;?>><?= $categoria ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-12">
                        <div class="form-group">
                            <label for="cidade">Cidade</label>
                            <div class="custom-select">
                                <select class="form-control" name="cidade" id="cidade">
                                    <option value="">Selecione</option>
                                    <?php foreach ($this->listas['Cidade'] as $cidade) : ?>
                                        <option value="<?= $cidade ?>"<?php if(array_key_exists('tipo', $params) && $params['cidade'] == $cidade):?> selected<?php endif;?>><?= $cidade ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-12">
                        <div class="form-group">
                            <label for="cidade">Bairros</label>
                            <div class="custom-select">
                                <select class="form-control" name="bairros" id="bairros">
                                    <option value="">Selecione</option>
                                    <?php foreach ($this->listas['Bairro'] as $bairro) : ?>
                                        <option value="<?= $bairro ?>"<?php if(array_key_exists('tipo', $params) && $params['bairros'] == $bairro):?> selected<?php endif;?>><?= $bairro ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-3 col-md-6">
                        <div class="form-group">
                            <label for="valor_min">Valor mín.</label>
                            <div class="custom-select">
                                <select class="form-control" name="valor_min" id="valor_min">
                                    <option value="">Qualquer</option>
                                    <option value="50000">R$ 50.000,000</option>
                                    <option value="100000">R$ 100.000,000</option>
                                    <option value="300000">R$ 300.000,000</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-3 col-md-6">
                        <div class="form-group">
                            <label for="valor_min">Valor max.</label>
                            <div class="custom-select">
                                <select class="form-control" name="valor_max" id="valor_max">
                                    <option value="">Qualquer</option>
                                    <option value="300000">R$ 300.000,000</option>
                                    <option value="600000">R$ 500.000,000</option>
                                    <option value="750000">R$ 750.000,000</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-12">
                        <div class="form-group">
                            <label for="valor_min">Dormitórios</label>
                            <input id="dormitorios" type="hidden" value="" name="dormitorios" />
                            <div id="dorm_search" class="btn-group clearfix" data-toggle="buttons">
                                <label class="btn btn-checkbox <?= in_array(1, $dorms) ? 'active' : ''?>">
                                    <input type="checkbox" autocomplete="off" data-qnt="1" <?= in_array(1, $dorms) ? 'checked' : ''?>><i>1</i>
                                </label>
                                <label class="btn btn-checkbox <?= in_array(2, $dorms) ? 'active' : ''?>">
                                    <input type="checkbox" autocomplete="off" data-qnt="2" <?= in_array(2, $dorms) ? 'checked' : ''?>><i>2</i>
                                </label>
                                <label class="btn btn-checkbox <?= in_array(3, $dorms) ? 'active' : ''?>">
                                    <input type="checkbox" autocomplete="off" data-qnt="3" <?= in_array(3, $dorms) ? 'checked' : ''?>><i>3</i>
                                </label>
                                <label class="btn btn-checkbox <?= in_array(4, $dorms) ? 'active' : ''?>">
                                    <input type="checkbox" autocomplete="off" data-qnt="4" <?= in_array(4, $dorms) ? 'checked' : ''?>><i>4</i>
                                </label>
                                <label class="btn btn-checkbox <?= in_array(5, $dorms) ? 'active' : ''?>">
                                    <input type="checkbox" autocomplete="off" data-qnt="5" <?= in_array(5, $dorms) ? 'checked' : ''?>><i>5+</i>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-12">
                        <div class="form-group">
                            <input type="submit" value="<?php echo !empty($this->buttonText) ? $this->buttonText : 'Buscar Imóveis'?>" class="btn-buscar"/>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="pesquisa-codigo">
            <div class="form-group">
                <form action="<?php echo $this->serverUrl().BASEDIR?>/imoveis/listagem">
                    <div class="fl-left">
                        <label for="input-codigo">Buscar por código</label>
                        <input type="text" id="input-codigo" name="codigo" placeholder="Digite aqui..."/>
                    </div>
                    <button type="submit"><i class="icon-search"></i></button>
                </form>
            </div>
        </div>
    </div>
</div>
<?php $this->headScript()->appendFile($this->serverUrl().BASEDIR.'/res/js/busca.js'); ?>
