<div class="container">
    <!--PESQUISA-->
    <?php echo $this->partial('index/busca_form.phtml', array(
        'listas' => $this->listas,
        'innerDivClass' => 'pesquisa-home',
        'buttonText' => 'Buscar Imóveis',
    )); ?>
    <!--/PESQUISA-->

    <!--SLIDE-->
    <?php echo $this->render('index/slider.phtml'); ?>
    <!--/SLIDE-->

    <!--WIDGETS HOME-->
    <section class="destaques-home">
        <?php if (count($this->widgets1)) echo $this->render('index/widget1.phtml'); ?>
        <?php if (count($this->widgets2)) echo $this->render('index/widget2.phtml'); ?>
    <!--/WIDGETS HOME-->
    </section>
</div>