<div class="container">
    <!--PESQUISA-->
    <?php echo $this->partial('index/busca_form.phtml', array(
        'listas' => $this->listas,
        'innerDivClass' => 'pesquisa-home',
        'buttonText' => 'Buscar Imóveis',
    )); ?>
    <!--/PESQUISA-->

    <!--SLIDE-->
    <?php echo $this->render('index/slider.phtml'); ?>
    <!--/SLIDE-->

    <!--LISTAGEM DE IMÓVEIS-->
    <?php echo $this->render('index/listagem.phtml'); ?>
    <!--/LISTAGEM DE IMÓVEIS-->
</div>