<div class="col-xs-12 col-md-8 col-lg-9 slide-home-container">
    <div class="slide-home">
        <div class="slide-in">
            <?php foreach ($this->banners as $banner) : ?>
                <div class="slide">
                    <a href="#">
                        <img src="<?= $banner['FotoDestaque']; ?>" alt="<?= $banner['Codigo']; ?>"/>
                        <div class="content-slider">
                            <h3><?= $banner['Empreendimento']; ?></h3>
                            <?php if (intval($banner['ValorVenda']) > 0) : ?>
                                <p>A partir de R$ <?= number_format($banner['ValorVenda'], 2, ',', '.'); ?></p>
                            <?php endif; ?>
                            <span href="<?php echo $this->serverUrl().BASEDIR?>/imoveis/detalhes/codigo/<?php echo $banner['Codigo']; ?>" class="btn-detalhes">VEJA DETALHES <i class="icon-arrow-left"></i></span>
                        </div>
                        <div class="shadow"></div>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="custom-nav-slide">
            <?php
            $current = 0;
            foreach ($this->banners as $banner) : ?>
                <a data-slide-index="<?= $current; ?>" href="">
                    <span class="custom-nav-link">
                        <?= $banner['Categoria'] .
                        (intval($banner['Dormitorios']) > 0 ? ' ' . $banner['Dormitorios'] : '')  .
                        '<br>' . $banner['Bairro'] . '/' . $banner['Cidade']; ?></span>
                    <span class="bar-progress"></span>
                </a>
            <?php
            $current++;
            endforeach; ?>
        </div>
    </div>
</div>