<div class="destaques-title">
    <h3 class="title-section"><strong>Casas</strong> para morar</h3>
    <span class="toggle-imoveis" data-content="destaques-2"><i class="icon-arrow-down"></i></span>
    <a href="<?= $this->serverURL() . BASEDIR ?>/imoveis/listagem?Categoria=Casa" class="ver-mais">Veja mais casas <i class="icon-arrow-left"></i></a>
</div>
<div class="destaques-content" data-target="destaques-2">
    <div class="row">
        <div class="col-xs-12">
            <div class="row">
                <?php
                $count = 0;
                foreach ($this->widget2 as $widget2) : ?>
                    <div class="col-xs-<?= ($count == 2 ? '6' : '3'); ?>">
                        <div class="destaque destaque-<?= ($count > 1 ? 'mid' : 'big') ?>">
                            <a href="<?= $this->serverURL() . BASEDIR ?>/imoveis/detalhes?codigo=<?= $widget2['Codigo']; ?>">
                                <div class="destaque-img" style="background-image: url(<?= $widget2['FotoDestaque']; ?>)"></div>
                                <div class="content-destaque">
                                    <span class="block destaque-tipo"><?= $widget2['Cateogira']; ?></span>
                                    <?php if (intval($widget2['Dormitorios']) > 0) :?>
                                        <h4 class="destaque-caracteristicas"><?= $widget2['Dormitorios']; ?> dormitórios</h4>
                                    <?php endif; ?>
                                    <span class="block destaque-preco">R$ <?= $widget2['ValorVenda']; ?></span>
                                    <span class="block destaque-codigo"><?= $widget2['Codigo']; ?></span>
                                </div>
                                <div class="shadow"></div>
                            </a>
                        </div>
                    </div>
                <?php
                    $count++;
                    if ($count >= 4) break;
                endforeach; ?>
            </div>
        </div>
    </div>
</div>
