<div class="container">
    <div class="span12">
        <div class="col-lg-9 col-md-8 col-sm-10 col-xs-12">

            <h2>Quem Somos</h2>
            <br>

            A <strong>Esselence Consultoria Imobiliária</strong> (Creci 37.465) é uma empresa composta por profissionais qualificados e atualizados com o mercado imobiliário, e tem como objetivo primordial atender plenamente os seus clientes na compra, venda, permuta ou locação de imóveis nas praias do Litoral Norte ( De Tramandaí­ a Torres ) e em Porto Alegre e Gramado.
            <br>
            A empresa é administrada e representada pelo seu Proprietário, Sr. Douglas Cardoso Nunes (Creci 37.465).
            <br>
            <h3><strong>FAZER A DIFERENÇA:</strong></h3>
            A implantação de um novo conceito em negócios imobiliários, o princípio máximo desta empresa, é uma tarefa árdua que exige muito trabalho e dedicação.
            Por isso, cada profissional desta empresa deve manter sempre o foco em:
            1º Tratar o cliente como se fosse o único;
            2° Ser honesto com todas as partes envolvidas;
            3° Prestar um serviço de excelência, visando acima de tudo a satisfação dos clientes;
            4° Buscar a cada dia as melhores oportunidades de negócios;
            5° NÃO ESQUECER- Nunca estamos sozinhos, existe alguém lá em cima que esta olhando para nós, mas também julgando nossos atos.
            <br>
            <h3><strong> META:</strong></h3>
            Ser referência em negócios imobiliários na região em que atuar.
            <br>
            <h3><strong>FILOSOFIA DA EMPRESA:</strong> </h3>
            Nem sempre o caminho mais fácil é o caminho correto.
            <br>
            <strong>LEMBRAR SEMPRE O ÚNICO LUGAR EM QUE O SUCESSO VEM ANTES DE TRABALHO É NO DICIONÁRIO.</strong>
            <br>
            A <strong>Esselence Consultoria Imobiliária</strong> possui todos os lançamentos de edifícios em construção pelas construtoras, que com o objetivo primordial de oferecer aos seus clientes todos os imóveis em construção ou já construídos.
            <br>
            Assim, a <strong>Esselence Consultoria Imobiliária</strong> juntamente com os seus colaboradores, coloca-se a disposição dos seus clientes, para que juntos possam concretizar o seu sonho e o de sua família.
            <br>
            Venha nos conhecer e fechar ótimos negócios!
            <br>
            <h3><strong>Esselence Consultoria Imobiliária</strong></h3>

        </div>
    </div>
</div>