
<h2>Quem Somos</h2>
<br>

<h3>A <strong>Esselence Consultoria Imobiliária</strong> (Creci 37.465) é uma empresa composta por profissionais qualificados e atualizados com o mercado imobiliário, e tem como objetivo primordial atender plenamente os seus clientes na compra, venda, permuta ou locação de imóveis nas praias do Litoral Norte ( De Tramandaí­ a Torres ) e em Porto Alegre e Gramado.</h3>
<br>
<h3>A empresa é administrada e representada pelo seu Proprietário, Sr. Douglas Cardoso Nunes (Creci 37.465).</h3>
<br>
<h3><strong>FAZER A DIFERENÇA:</strong></h3>
<h3>A implantação de um novo conceito em negócios imobiliários, o princípio máximo desta empresa, é uma tarefa árdua que exige muito trabalho e dedicação.</h3>
<h3>Por isso, cada profissional desta empresa deve manter sempre o foco em:</h3>
<h3>1º Tratar o cliente como se fosse o único;</h3>
<h3>2° Ser honesto com todas as partes envolvidas;</h3>
<h3>3° Prestar um serviço de excelência, visando acima de tudo a satisfação dos clientes;</h3>
<h3>4° Buscar a cada dia as melhores oportunidades de negócios;</h3>
<h3>5° NÃO ESQUECER- Nunca estamos sozinhos, existe alguém lá em cima que esta olhando para nós, mas também julgando nossos atos.</h3>
<br>
<h3><strong> META:</strong></h3>
<h3>Ser referência em negócios imobiliários na região em que atuar.</h3>
<br>
<h3><strong>FILOSOFIA DA EMPRESA:</strong> </h3>
<h3>Nem sempre o caminho mais fácil é o caminho correto.</h3>
<br>
<h3><strong>LEMBRAR SEMPRE O ÚNICO LUGAR EM QUE O SUCESSO VEM ANTES DE TRABALHO É NO DICIONÁRIO.</strong></h3>
<br>
<h3>A <strong>Esselence Consultoria Imobiliária</strong> possui todos os lançamentos de edifícios em construção pelas construtoras, que com o objetivo primordial de oferecer aos seus clientes todos os imóveis em construção ou já construídos.</h3>
<br>
<h3>Assim, a <strong>Esselence Consultoria Imobiliária</strong> juntamente com os seus colaboradores, coloca-se a disposição dos seus clientes, para que juntos possam concretizar o seu sonho e o de sua família.</h3>
<br>
<h3>Venha nos conhecer e fechar ótimos negócios!</h3>
<br>
<h3><strong>Esselence Consultoria Imobiliária</strong></h3>
<br>
<br>
<br>

