<!DOCTYPE html>
<html>
<head lang="pt-BR">
    <title>64 imóveis encontrados. Esselence Imóveis | Tramandaí, RS</title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Esselence Imóveis em Tramandaí - RS, Imóveis em Tramandaí, Imóveis no litoral Norte do RS, Venda de imóveis, Apartamentos, Casas, Terrenos, Lançamentos">
    <meta name="revisit-after" content="1" />
    <meta name="language" content="pt-br" />

    <link rel="shortcut icon" href="favicon.ico">

    <link rel="stylesheet" href="res/css/style.css"/>
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700' rel='stylesheet' type='text/css'>


    <div id="fb-root"></div>
    <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.4&appId=712673535512368";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
</head>
<body>

<!--HEADER-->
<header class="header-site">
    <div class="nav-bar">
        <div class="container">
            <button type="button" class="open-menu"><i class="icon-menu"></i></button>
            <div class="logo">
                <a href="#"><img src="res/imgs/logo.png" alt="Esselence"/></a>
            </div>
            <div class="menu">
                <nav class="nav-main">
                    <ul>
                        <li><a href="#">Lançamentos</a></li>
                        <li><a href="#">Imóveis à venda</a></li>
                        <li><a href="#">Fale conosco</a></li>
                    </ul>
                </nav>
                <div class="nav-secondary">
                    <div>
                        <a href="#">Quem somos</a>
                    </div>
                    <div>
                        <a href="#">Anuncie seu imóvel</a>
                    </div>
                    <div>
                        <a href="#">Financiamento</a>
                    </div>
                </div>
            </div>
            <div class="fone-header">
                <a href="tel:51 3661 1040"><img src="res/imgs/telefone.png" alt="Telefone"/></a>
                <img src="res/imgs/telefone.png" alt="Telefone"/>
                <span class="fone-text">
                    Ligue agora
                    <strong>51 3661 1040</strong>
                </span>
            </div>
        </div>
    </div>
</header>
<!--/HEADER-->

<section class="body-site" style="overflow:hidden">
    <div class="container">
        <div class="row">
            <!-- TÍTULO -->
            <div class="col-lg-9 col-md-8 col-sm-10 col-xs-12">
                <div class="title-main">
                    <div class="row">
                        <div class="col-md-8 col-sm-8 col-xs-12">
                            <h2>64 imóveis encontrados</h2>
                        </div>

                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <div class="form-group range">
                                <label>Ordenar por</label>
                                <div class="custom-select">
                                    <select class="form-control" name="tipo" id="tipo">
                                        <option value="">Escolha uma opção</option>
                                        <option value="">Tipo</option>
                                        <option value="">Maior valor</option>
                                        <option value="">Menor valor</option>
                                        <option value="">Cidade</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /TÍTULO -->

            <!-- LISTAGEM -->
            <div class="col-lg-9 col-md-8 col-sm-10 col-xs-12">
                <section class="imoveis-list">
                    <div class="row">
                        <div class="col-md-4 col-sm-4 col-xs-6">
                            <div class="imovel-list">
                                <a href="#" title="Apartamento, Humaitá, Tramandaí, RS">
                                    <span class="codigo">ES00113</span>
                                    <div class="imovel-picture" style="background:url(http://revistaimoveis.zap.com.br/imoveis/2012/10/casa-aluguel1.jpg)"></div>
                                    <label>Apartamento</label>
                                    <span class="local">Humaitá, Tramandaí</span>
                                    <span class="caracteristicas">2 dormitórios • 84m&sup2;</span>
                                    <span class="preco">R$ 215.000,00</span>
                                </a>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-4 col-xs-6">
                            conteudo
                        </div>
                        <div class="col-md-3 col-sm-4 col-xs-6">
                            conteudo
                        </div>
                        <div class="col-md-3 col-sm-4 col-xs-6">
                            conteudo
                        </div>
                        <div class="col-md-3 col-sm-4 col-xs-6">
                            conteudo
                        </div>
                        <div class="col-md-3 col-sm-4 col-xs-6">
                            conteudo
                        </div>
                    </div>
                </section>
            </div>
            <!-- /LISTAGEM -->

            <!-- FORM PESQUISA -->
            <div class="pesquisa-container col-lg-3 col-md-4">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="pesquisa-imoveis">
                            <div class="formulario">
                                <h2>Encontre seu imóvel</h2>
                                <div class="row">
                                    <div class="col-xs-12 col-sm-6 col-md-12">
                                        <div class="form-group">
                                            <label for="tipo">Tipos</label>
                                            <div class="custom-select">
                                                <select class="form-control" name="tipo" id="tipo">
                                                    <option value="">Selecione</option>
                                                    <option value="">Apartamento</option>
                                                    <option value="">Casa</option>
                                                    <option value="">Terreno</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-6 col-md-12">
                                        <div class="form-group">
                                            <label for="cidade">Cidade</label>
                                            <div class="custom-select">
                                                <select class="form-control" name="cidade" id="cidade">
                                                    <option value="">Selecione</option>
                                                    <option value="">Apartamento</option>
                                                    <option value="">Casa</option>
                                                    <option value="">Terreno</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-6 col-md-12">
                                        <div class="form-group">
                                            <label for="cidade">Bairros</label>
                                            <div class="custom-select">
                                                <select class="form-control" name="bairros" id="bairros">
                                                    <option value="">Selecione</option>
                                                    <option value="">Apartamento</option>
                                                    <option value="">Casa</option>
                                                    <option value="">Terreno</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xs-6 col-sm-3 col-md-6">
                                        <div class="form-group">
                                            <label for="valor_min">Valor mín.</label>
                                            <div class="custom-select">
                                                <select class="form-control" name="valor_min" id="valor_min">
                                                    <option value="">100.000</option>
                                                    <option value="">200.000</option>
                                                    <option value="">300.000</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xs-6 col-sm-3 col-md-6">
                                        <div class="form-group">
                                            <label for="valor_min">Valor max.</label>
                                            <div class="custom-select">
                                                <select class="form-control" name="valor_max" id="valor_max">
                                                    <option value="">100.000</option>
                                                    <option value="">200.000</option>
                                                    <option value="">300.000</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-6 col-md-12">
                                        <div class="form-group">
                                            <label for="valor_min">Dormitórios</label>
                                            <div class="btn-group clearfix" data-toggle="buttons">
                                                <label class="btn btn-checkbox">
                                                    <input type="checkbox" autocomplete="off"><i>1</i>
                                                </label>
                                                <label class="btn btn-checkbox">
                                                    <input type="checkbox" autocomplete="off"><i>2</i>
                                                </label>
                                                <label class="btn btn-checkbox">
                                                    <input type="checkbox" autocomplete="off"><i>3</i>
                                                </label>
                                                <label class="btn btn-checkbox">
                                                    <input type="checkbox" autocomplete="off"><i>4</i>
                                                </label>
                                                <label class="btn btn-checkbox">
                                                    <input type="checkbox" autocomplete="off"><i>5+</i>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-6 col-md-12">
                                        <div class="form-group">
                                            <input type="submit" value="Buscar novamente" class="btn-buscar"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="pesquisa-codigo">
                                <div class="form-group">
                                    <div class="fl-left">
                                        <label for="input-codigo">Buscar por código</label>
                                        <input type="text" id="input-codigo" name="input-codigo" placeholder="Digite aqui..."/>
                                    </div>
                                    <button type="submit"><i class="icon-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /FORM PESQUISA -->

        </div>

    </div>
</section>


<footer class="footer-site">
    <div class="footer-fone">
        <div class="container">
            <h6>
                <img src="res/imgs/telefone-branco.png" alt="Telefone"/>
                LIGUE AGORA <strong>51 3661 1040</strong>
            </h6>
        </div>
    </div>
    <div class="footer-content">
        <div class="container">
            <div class="logo-footer">
                <a href="#"><img src="res/imgs/logo.png" alt="Esselence"/></a>
            </div>
            <div class="address-footer">
                <address>
                    Rua Fernando Amaral, 1038 - Sala 01 - Tramandaí - RS<br/>
                    Telefone: 51 3661 1040
                </address>
                <a href="mailto:vendas@esselence.com.br">vendas@esselence.com.br</a>
            </div>
            <div class="facebook-plugin">
                <span class="icon-facebook"></span>
                <div class="fb-page" data-href="https://www.facebook.com/www.esselence.com.br?fref=ts" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="false" data-show-posts="false"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/www.esselence.com.br?fref=ts"><a href="https://www.facebook.com/www.esselence.com.br?fref=ts">Esselence Consultoria Imobiliária</a></blockquote></div></div>
            </div>
        </div>
    </div>
</footer>
</body>
<script src="res/js/main.min.js"></script>
</html>