<header class="head-imo">

    <div class="container">
        <div class="fl-left">
            <h2 class="head-imo-info"><?php echo $this->imovel['Categoria']?> <?php echo $this->imovel['Dormitorios']?> dormitórios, <?php echo $this->imovel['Bairro']?>, <?php echo $this->imovel['Cidade']?> <small>Código: <?php echo $this->imovel['Codigo']?></small></h2>
        </div>
        <div class="fl-right">
            <div class="compartilhe">
                Compartilhe:
                <a onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=<?php echo $this->serverUrl() . BASEDIR . '/imoveis/detalhes/codigo/' . $this->imovel['Codigo']?>&title=esselence','name','width=600,height=400')" href="#" data-title="Facebook" data-desc="test" data-image="test" class="facebook"><span class="icon-facebook"></span></a>
                <a href="#" title="Enviar por e-mail" class="mail"><span class="icon-mail"></span></a>
            </div>
        </div>

        <div class="row no-padding">
            <div class="col-xs-12 col-md-8 col-lg-9">
                <div class="galeria-imovel">
                    <div id="slider" class="slider flexslider">
                        <ul class="slides">
                            <?php foreach($this->imovel['Foto'] as $value):?>
                                <li>
                                    <div class="img-container">
                                        <span>
                                            <img src="<?php echo $value['Foto']?>"/>
                                        </span>
                                    </div>
                                </li>
                            <?php endforeach;?>
                        </ul>
                    </div>
                    <div id="carousel" class="carousel flexslider">
                        <ul class="slides">
                            <?php foreach($this->imovel['Foto'] as $value):?>
                                <li>
                                    <img src="<?php echo $value['Foto']?>"/>
                                </li>
                            <?php endforeach;?>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-md-4 col-lg-3">
                <div class="info-imovel">
                    <h2><?php echo $this->imovel['Empreendimento']?></h2>
                    <div class="info-imovel-txt">
                        <div class="row">
                            <div class="col-xs-6"><p><strong>Tipo</strong></p></div>
                            <div class="col-xs-6"><p><?php echo $this->imovel['Categoria']?></p></div>

                            <div class="col-xs-6"><p><strong>Bairro</strong></p></div>
                            <div class="col-xs-6"><p><?php echo $this->imovel['Bairro']?></p></div>

                            <div class="col-xs-6"><p><strong>Cidade</strong></p></div>
                            <div class="col-xs-6"><p><?php echo $this->imovel['Cidade']?></p></div>

                            <?php if (intval($this->imovel['Dormitorios']) > 0) : ?>
                                <div class="col-xs-6"><p><strong>Dormitórios</strong></p></div>
                                <div class="col-xs-6"><p><?php echo $this->imovel['Dormitorios']?></p></div>
                            <?php endif; ?>

                            <?php if (intval($this->imovel['Suites']) > 0) : ?>
                                <div class="col-xs-6"><p><strong>Suítes</strong></p></div>
                                <div class="col-xs-6"><p><?php echo $this->imovel['Suites']?></p></div>
                            <?php endif; ?>

                            <?php if (intval($this->imovel['Vagas']) > 0) : ?>
                                <div class="col-xs-6"><p><strong>Vagas</strong></p></div>
                                <div class="col-xs-6"><p><?php echo $this->imovel['Vagas']?></p></div>
                            <?php endif; ?>

                            <?php if (intval($this->imovel['AreaPrivativa']) > 0) : ?>
                                <div class="col-xs-6"><p><strong>Área privativa</strong></p></div>
                                <div class="col-xs-6"><p><?php echo $this->imovel['AreaPrivativa']?> m²</p></div>
                            <?php endif; ?>

                            <?php if (intval($this->imovel['AreaTotal']) > 0) : ?>
                                <div class="col-xs-6"><p><strong>Área total</strong></p></div>
                                <div class="col-xs-6"><p><?php echo $this->imovel['AreaTotal']?> m²</p></div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php if (intval($this->imovel['ValorVenda']) > 0) : ?>
                        <div class="info-imovel-preco">
                            <small>VALOR DO IMÓVEL</small>
                            <h3>R$ <?php echo number_format($this->imovel['ValorVenda'], 2, ',','.')?></h3>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</header>
<section class="content-imo">
    <div class="container">
        <div class="row descricao-imovel">
            <div class="col-xs-12 col-md-4">
                <div class="sub-title-container">
                    <h3 class="sub-title">Descrição do imóvel</h3>
                </div>
                <p><?php echo $this->imovel['Descricao']; ?></p>
            </div>
            <div class="col-xs-12 col-md-8">
                <div class="sub-title-container">
                    <h3 class="sub-title">Características</h3>
                </div>
                <ul class="row">
                    <?php foreach($this->imovel['Caracteristicas'] as $key => $value):?>
                        <?php if(is_numeric($value) && $value > 0):?>
                            <li class="col-sm-6 col-md-6 col-lg-4"><?php echo "{$value} {$key}"?></li>
                        <?php elseif($value == 'Sim'):?>
                            <li class="col-sm-6 col-md-6 col-lg-4"><?php echo $key?></li>
                        <?php endif;?>
                    <?php endforeach;?>
                </ul>
            </div>
        </div>
        <div class="mapa-imovel">
            <div class="mapa-container" id="mapa-imovel">
            </div>
        </div>
    </div>

    <div class="contato-imovel">
        <?php echo $this->render('/fale-conosco/contato-form.phtml')?>
    </div>
</section>
<script>
    GMaps.mapLatitude  = '<?php echo $this->imovel['Latitude'];  ?>';
    GMaps.mapLongitude = '<?php echo $this->imovel['Longitude']; ?>';
</script>