<section class="destaques-home">
    <div class="destaques-title">
        <h3 class="title-section"><strong>Apartamentos</strong> de 2 e 3 dormitórios</h3>
        <span class="toggle-imoveis is-active" data-content="destaques-1"><i class="icon-arrow-down"></i></span>
        <a href="#" class="ver-mais">Veja mais apartamentos <i class="icon-arrow-left"></i></a>
    </div>
    <div class="destaques-content is-active" data-target="destaques-1">
        <div class="row">
            <div class="col-xs-12">
                <div class="row">
                    <div class="col-xs-6">
                        <div class="destaque destaque-big">
                            <a href="#">
                                <div class="destaque-img" style="background-image: url(https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=160&h=240)"></div>
                                <div class="content-destaque">
                                    <span class="block destaque-tipo">Apartamento</span>
                                    <h4 class="destaque-caracteristicas">2 dormitórios</h4>
                                    <span class="block destaque-preco">R$ 500.000,00</span>
                                    <span class="block destaque-codigo">E1234</span>
                                </div>
                                <div class="shadow"></div>
                            </a>
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <div class="destaque destaque-mid">
                            <a href="#">
                                <div class="destaque-img" style="background-image: url(https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=160&h=240)"></div>
                                <div class="content-destaque">
                                    <span class="block destaque-tipo">Apartamento</span>
                                    <h4 class="destaque-caracteristicas">2 dormitórios</h4>
                                    <span class="block destaque-preco">R$ 500.000,00</span>
                                    <span class="block destaque-codigo">E1234</span>
                                </div>
                                <div class="shadow"></div>
                            </a>
                        </div>
                        <div class="destaque destaque-mid">
                            <a href="#">
                                <div class="destaque-img" style="background-image: url(https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=160&h=240)"></div>
                                <div class="content-destaque">
                                    <span class="block destaque-tipo">Apartamento</span>
                                    <h4 class="destaque-caracteristicas">2 dormitórios</h4>
                                    <span class="block destaque-preco">R$ 500.000,00</span>
                                    <span class="block destaque-codigo">E1234</span>
                                </div>
                                <div class="shadow"></div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
                <div class="destaque destaque-big">
                    <a href="#">
                        <div class="destaque-img" style="background-image: url(https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=160&h=240)"></div>
                        <div class="content-destaque content-destaque-big">
                            <span class="block destaque-tipo">Apartamento</span>
                            <h4 class="destaque-caracteristicas">2 dormitórios</h4>
                            <span class="block destaque-preco">R$ 500.000,00</span>
                            <span class="block destaque-codigo">E1234</span>
                        </div>
                        <div class="shadow"></div>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="destaques-title">
        <h3 class="title-section"><strong>Casas</strong> para morar</h3>
        <span class="toggle-imoveis" data-content="destaques-2"><i class="icon-arrow-down"></i></span>
        <a href="#" class="ver-mais">Veja mais casas <i class="icon-arrow-left"></i></a>
    </div>
    <div class="destaques-content" data-target="destaques-2">
        <div class="row">
            <div class="col-xs-12">
                <div class="row">
                    <div class="col-xs-3">
                        <div class="destaque destaque-mid">
                            <a href="#">
                                <div class="destaque-img" style="background-image: url(https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=160&h=240)"></div>
                                <div class="content-destaque">
                                    <span class="block destaque-tipo">Apartamento</span>
                                    <h4 class="destaque-caracteristicas">2 dormitórios</h4>
                                    <span class="block destaque-preco">R$ 500.000,00</span>
                                    <span class="block destaque-codigo">E1234</span>
                                </div>
                                <div class="shadow"></div>
                            </a>
                        </div>
                        <div class="destaque destaque-mid">
                            <a href="#">
                                <div class="destaque-img" style="background-image: url(https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=160&h=240)"></div>
                                <div class="content-destaque">
                                    <span class="block destaque-tipo">Apartamento</span>
                                    <h4 class="destaque-caracteristicas">2 dormitórios</h4>
                                    <span class="block destaque-preco">R$ 500.000,00</span>
                                    <span class="block destaque-codigo">E1234</span>
                                </div>
                                <div class="shadow"></div>
                            </a>
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <div class="destaque destaque-big">
                            <a href="#">
                                <div class="destaque-img" style="background-image: url(https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=160&h=240)"></div>
                                <div class="content-destaque content-destaque-big">
                                    <span class="block destaque-tipo">Apartamento</span>
                                    <h4 class="destaque-caracteristicas">2 dormitórios</h4>
                                    <span class="block destaque-preco">R$ 500.000,00</span>
                                    <span class="block destaque-codigo">E1234</span>
                                </div>
                                <div class="shadow"></div>
                            </a>
                        </div>
                    </div>
                    <div class="col-xs-3">
                        <div class="destaque destaque-big">
                            <a href="#">
                                <div class="destaque-img" style="background-image: url(https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=160&h=240)"></div>
                                <div class="content-destaque">
                                    <span class="block destaque-tipo">Apartamento</span>
                                    <h4 class="destaque-caracteristicas">2 dormitórios</h4>
                                    <span class="block destaque-preco">R$ 500.000,00</span>
                                    <span class="block destaque-codigo">E1234</span>
                                </div>
                                <div class="shadow"></div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>