<?php foreach($this->imoveis as $key => $value):?>
<?php if(!is_array($value)) continue;?>
    <div class="col-lg-4 col-md-6 col-sm-4">
        <div class="imovel-list">
            <a href="<?php echo $this->serverUrl().BASEDIR?>/imoveis/detalhes/codigo/<?php echo $value['Codigo']?>" title="<?php echo "{$value['Categoria']}, {$value['Bairro']}, {$value['Cidade']}"?>">
                <span class="codigo"><?php echo $value['Codigo']?></span>
                <div class="imovel-picture" style="background:url(<?php echo $value['FotoDestaque']?>)"></div>
                <label><?php echo $value['Categoria']?></label>
                <span class="local"><?php echo $value['Bairro']?>, <?php echo $value['Cidade']?></span>
                <span class="caracteristicas"><?php echo $value['Dormitorios']?> dormitórios • <?php echo $value['AreaTotal']?>&sup2;</span>
                <span class="preco">R$ <?php echo number_format($value['ValorVenda'], 2, ',','.')?></span>
            </a>
        </div>
    </div>
<?php endforeach;?>