<div class="container">
    <div class="row">
        <!-- TÍTULO -->
        <div class="col-lg-9 col-md-8 col-sm-10 col-xs-12">
            <div class="title-main">
                <div class="row">
                    <div class="col-md-8 col-sm-8 col-xs-12">
                        <h2><?php echo $this->quantidadeImoveis?> imóveis encontrados</h2>
                    </div>

                    <div class="col-md-4 col-sm-4 col-xs-12">
                        <div class="form-group range">
                            <label>Ordenar por</label>
                            <div class="custom-select">
                                <select class="form-control" name="tipo" id="tipo">
                                    <option value="">Escolha uma opção</option>
                                    <option value="">Tipo</option>
                                    <option value="">Maior valor</option>
                                    <option value="">Menor valor</option>
                                    <option value="">Cidade</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /TÍTULO -->

        <!-- LISTAGEM -->
        <div class="col-lg-9 col-md-8 col-sm-10 col-xs-12">
            <section class="imoveis-list">
                <div class="row">
                    <?php foreach($this->imoveis as $key => $value):?>
                        <?php if(!is_array($value)) continue;?>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                            <div class="imovel-list">
                                <a href="#" title="Apartamento, Humaitá, Tramandaí, RS">
                                    <span class="codigo"><?php echo $value['Codigo']?></span>
                                    <div class="imovel-picture" style="background:url(<?php echo $value['FotoDestaque']?>)"></div>
                                    <label><?php echo $value['Categoria']?></label>
                                    <span class="local"><?php echo $value['Bairro']?>, <?php echo $value['Cidade']?></span>
                                    <span class="caracteristicas"><?php echo $value['Dormitorios']?> dormitórios • <?php echo $value['AreaTotal']?>&sup2;</span>
                                    <span class="preco">R$ <?php echo number_format($value['ValorVenda'], 2, ',','.')?></span>
                                </a>
                            </div>
                        </div>
                    <?php endforeach;?>
                </div>
            </section>
        </div>
        <!-- /LISTAGEM -->

        <!-- FORM PESQUISA -->
        <?php echo $this->partial('index/busca_form.phtml', array(
            'listas' => $this->listas,
            'innerDivClass' => 'pesquisa-imoveis',
            'buttonText' => 'Buscar novamente',
        )); ?>
        <!-- /FORM PESQUISA -->

    </div>

</div>