<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>ENTRE EM CONTATO!</h2>
            <div class="descricao-imovel">
                <p>A Esselence conta com uma equipe de corretores especializados prontos para resolver suas questões. Entre em contato conosco, ou se preferir, agende uma visita para conhecer o imóvel pessoalmente.</p>
            </div>
        </div>
        <div class="col-md-8">
            <div class="row">
                <form action="<?php echo $this->serverUrl().BASEDIR?>/fale-conosco"" method="post">
                <div class="col-xs-12 col-sm-6 col-md-5">
                    <div class="form-group">
                        <label for="nome">Nome</label>
                        <input type="text" id="nome" name="nome" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="fone">Telefone</label>
                        <input type="text" id="fone" name="fone" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="email">E-mail</label>
                        <input type="email" id="email" name="email" class="form-control">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-7">
                    <div class="form-group">
                        <label for="mensagem">Mensagem</label>
                        <textarea name="mensagem" id="mensagem" cols="30" rows="10" class="form-control"></textarea>
                    </div>
                </div>
                <div class="col-xs-12">
                    <input type="submit" value="Enviar mensagem" class="btn-buscar">
                </div>
                </form>
            </div>
        </div>
    </div>
</div>